unbind C-b
set -g prefix C-b

###################### [OPTIONS] ######################
set -g mouse on
set -g history-limit 100000
set -g base-index 1
set-option -gw xterm-keys on
set-window-option -g pane-base-index 1
# set-window-option -g mode-keys vi

###################### [RESOURCE] ######################
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config file"

###################### [WINDOWS] ######################
unbind n # DEFAULT: next-window
unbind p # DEFAULT: previous-window

unbind c # DEFAULT: new-window
unbind , # DEFAULT: rename-window


unbind w # DEFAULT: list-windows

unbind v
unbind h
unbind % # DEFAULT: split-window -h
unbind '"' # DEFAULT: split-window -v

unbind -n M-l
unbind -n M-h
unbind -n M-j
unbind -n M-k

# [SPLIT WINDOW]
bind v split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# [ RENAME|CREATE WINDOW ]
bind n command-prompt "rename-window '%%'"
bind w new-window -c "#{pane_current_path}"

# [NAVIGATION PANEL] 
bind C-h select-pane -L
# bind -n C-j select-pane -D
# bind -n C-k select-pane -U
bind C-l select-pane -R

# [NAVIGATION WINDOWS] 
bind -n M-i previous-window
bind -n M-o next-window

unbind -n Tab
