#!/bin/sh

selected=$(fd . ~/dev -t d --exact-depth 1 | fzf)

if [ -z "$selected" ]; then
	exit 0
fi

# 0 Error | 1 Fine

session_name=$(basename $selected | tr . _)

tmux new -s $session_name -c $selected
